const WeekDay = [
  {
    id: '1',
    title: 'Jaya Mangala Gatha',
    category: 'Religous',
    time: '5:00 AM - 05:10 AM',
  },
  {
    id: '2',
    title: 'Seth Pirith',
    category: 'Religous',
    time: '05:11 AM - 05:30 AM',
  },
  {
    id: '3',
    title: 'Catholic Prayers',
    category: 'Religous',
    time: '05:31 AM - 05:50 AM',
  },
  {
    id: '4',
    title: 'Sadaham Sithuwili',
    category: 'Religous',
    time: '05:51 AM - 05:59 AM',
  },
  {
    id: '5',
    title: 'Sr. Selinta Thought for the Day',
    category: 'Religous',
    time: '06:00 AM - 06:10 AM',
  },
  {
    id: '6',
    title: 'Ayobowan Seth',
    category: 'Entertainment',
    time: '06:11 AM - 07:29 AM',
  },
  {
    id: '7',
    title: 'Paththara Wisthara',
    category: 'Newspaper',
    time: '07:30 AM - 08:00 AM',
  },
  {
    id: '8',
    title: 'Atha Dahaya',
    category: 'Entertainment',
    time: '08:00 AM - 09:00 AM',
  },
  {
    id: '9',
    title: 'Hourly News',
    category: 'News',
    time: '09:00 AM - 09:05 AM',
  },
  {
    id: '10',
    title: 'Atha Dahaya',
    category: 'Entertainment',
    time: '09:06 AM - 10:00 AM',
  },
  {
    id: '11',
    title: 'Hourly News',
    category: 'News',
    time: '10:00 AM - 10:05 AM',
  },
  {
    id: '12',
    title: 'Gee Sandalla',
    category: 'Entertainment',
    time: '10:06 AM - 12:00 PM',
  },

  {
    id: '13',
    title: 'Thunkala Aradhanawa',
    category: 'Religous',
    time: '12:00 PM - 12:10 PM',
  },
  {
    id: '14',
    title: 'Lunch Time Music',
    category: 'Entertainment',
    time: '12:11 PM - 12:45 PM',
  },
  {
    id: '15',
    title: 'Main News',
    category: 'News',
    time: '12:45 PM - 01:00 PM',
  },
  {
    id: '16',
    title: 'Back-to-Back',
    category: 'Entertainment',
    time: '01:00 PM - 03:00 PM',
  },
  {
    id: '17',
    title: 'Dewa Dayawa',
    category: 'Religous',
    time: '03:00 PM - 03:29 PM',
  },
  {
    id: '18',
    title: 'Daily Mass',
    category: 'Religous',
    time: '03:30 PM - 04:30 PM',
  },
  {
    id: '19',
    title: 'Nowina',
    category: 'News',
    time: '04:30 PM - 05:00 PM',
  },
  {
    id: '20',
    title: 'Hourly News',
    category: 'News',
    time: '05:00 PM - 05:05 PM',
  },
  {
    id: '21',
    title: 'Seth Evening Request',
    category: 'Entertainment',
    time: '05:00 PM - 06:00 PM',
  },
  {
    id: '22',
    title: 'Hourly News',
    category: 'News',
    time: '06:00 PM - 06:05 PM',
  },
  {
    id: '23',
    title: 'Seth Evening Request',
    category: 'Entertainment',
    time: '06:06 PM - 06:59 PM',
  },
  {
    id: '24',
    title: 'Catholic Spiritual Program',
    category: 'Religous',
    time: '07:00 PM - 08:00 PM',
  },
  {
    id: '25',
    title: 'Emmaus',
    category: 'Religous',
    time: '08:01 PM - 09:00 PM',
  },
  {
    id: '26',
    title: 'Catholic Hymns',
    category: 'Religous',
    time: '09:10 PM - 09:15 PM',
  },
  {
    id: '27',
    title: 'Seth Main News',
    category: 'News',
    time: '09:15 PM - 09:25 PM',
  },
  {
    id: '28',
    title: 'Holy Rosary',
    category: 'Religous',
    time: '09:30 PM - 10:30 PM',
  },
  {
    id: '29',
    title: 'Night Religous program',
    category: 'Religous',
    time: '10:30 PM - 11:00 PM',
  },
  {
    id: '30',
    title: 'Holy Hour',
    category: 'Religous',
    time: '11:00 PM - 12:00 AM',
  },
  {
    id: '31',
    title: 'Daily Mass - Repeat ',
    category: 'Entertainment',
    time: '12:00 AM - 01:00 AM',
  },
  {
    id: '32',
    title: 'Religous Programs',
    category: 'Entertainment',
    time: '12:00 AM - 01:00 AM',
  },
];
const Saturday = [
  {
    id: '1',
    title: 'Jaya Mangala Gatha',
    category: 'Religous',
    time: '5:00 AM - 05:10 AM',
  },
  {
    id: '2',
    title: 'Seth Pirith',
    category: 'Religous',
    time: '05:11 AM - 05:30 AM',
  },
  {
    id: '3',
    title: 'Catholic Prayers',
    category: 'Religous',
    time: '05:31 AM - 05:50 AM',
  },
  {
    id: '4',
    title: 'Sadaham Sithuwili',
    category: 'Religous',
    time: '05:51 AM - 05:59 AM',
  },
  {
    id: '5',
    title: 'Sr. Selinta Thought for the Day',
    category: 'Religous',
    time: '06:00 AM - 06:10 AM',
  },
  {
    id: '6',
    title: 'Ayobowan Seth',
    category: 'Entertainment',
    time: '06:11 AM - 07:29 AM',
  },
  {
    id: '7',
    title: 'Paththara Wisthara',
    category: 'Newspaper',
    time: '07:30 AM - 08:00 AM',
  },
  {
    id: '8',
    title: 'Music',
    category: 'Entertainment',
    time: '08:00 AM - 09:00 AM',
  },
  {
    id: '9',
    title: 'Hourly News',
    category: 'News',
    time: '09:00 AM - 09:05 AM',
  },
  {
    id: '10',
    title: 'Music',
    category: 'Entertainment',
    time: '09:06 AM - 10:00 AM',
  },
  {
    id: '11',
    title: 'Hourly News',
    category: 'News',
    time: '10:00 AM - 10:05 AM',
  },
  {
    id: '12',
    title: 'Gee Sandalla',
    category: 'Entertainment',
    time: '10:06 AM - 12:00 PM',
  },

  {
    id: '13',
    title: 'Thunkala Aradhanawa',
    category: 'Religous',
    time: '12:00 PM - 12:10 PM',
  },
  {
    id: '14',
    title: 'Lunch Time Music',
    category: 'Entertainment',
    time: '12:11 PM - 12:45 PM',
  },
  {
    id: '15',
    title: 'Main News',
    category: 'News',
    time: '12:45 PM - 01:00 PM',
  },
  {
    id: '16',
    title: 'Back-to-Back',
    category: 'Entertainment',
    time: '01:00 PM - 02:00 PM',
  },
  {
    id: '17',
    title: 'Menn Ape Iskole',
    category: 'Children',
    time: '02:00 PM - 03:00 PM',
  },
  {
    id: '18',
    title: 'Dewa Dayawa',
    category: 'Religous',
    time: '03:00 PM - 03:29 PM',
  },
  {
    id: '19',
    title: 'Daily Mass',
    category: 'Religous',
    time: '03:30 PM - 04:30 PM',
  },
  {
    id: '20',
    title: 'Nowina',
    category: 'News',
    time: '04:30 PM - 05:00 PM',
  },
  {
    id: '21',
    title: 'Hourly News',
    category: 'News',
    time: '05:00 PM - 05:05 PM',
  },
  {
    id: '22',
    title: 'Gee Sandalla',
    category: 'Entertainment',
    time: '05:06 PM - 06:00 PM',
  },
  {
    id: '23',
    title: 'Hourly News',
    category: 'News',
    time: '06:00 PM - 06:05 PM',
  },
  {
    id: '24',
    title: 'Seth Evening Request',
    category: 'Entertainment',
    time: '06:06 PM - 06:59 PM',
  },
  {
    id: '25',
    title: 'Catholic Spiritual Program',
    category: 'Religous',
    time: '07:00 PM - 08:00 PM',
  },
  {
    id: '26',
    title: 'Emmaus',
    category: 'Religous',
    time: '08:01 PM - 09:00 PM',
  },
  {
    id: '27',
    title: 'Catholic Hymns',
    category: 'Religous',
    time: '09:10 PM - 09:15 PM',
  },
  {
    id: '28',
    title: 'Seth Main News',
    category: 'News',
    time: '09:15 PM - 09:30 PM',
  },
  {
    id: '29',
    title: 'Holy Rosary',
    category: 'Religous',
    time: '09:30 PM - 10:30 PM',
  },
  {
    id: '30',
    title: 'Night Religous program',
    category: 'Religous',
    time: '10:30 PM - 11:00 PM',
  },
  {
    id: '31',
    title: 'Holy Hour',
    category: 'Religous',
    time: '11:00 PM - 12:00 AM',
  },
  {
    id: '32',
    title: 'Daily Mass - Repeat',
    category: 'Religous',
    time: '12:00 AM - 01:00 AM',
  },
  {
    id: '33',
    title: 'Religous programs',
    category: 'Entertainment',
    time: '01:00 AM - 04:59 AM',
  },
];
const Sunday = [
  {
    id: '1',
    title: 'Jaya Mangala Gatha',
    category: 'Religous',
    time: '5:00 AM - 05:10 AM',
  },
  {
    id: '2',
    title: 'Seth Pirith',
    category: 'Religous',
    time: '05:11 AM - 05:30 AM',
  },
  {
    id: '3',
    title: 'Catholic Prayers',
    category: 'Religous',
    time: '05:31 AM - 05:50 AM',
  },
  {
    id: '4',
    title: 'Sadaham Sithuwili',
    category: 'Religous',
    time: '05:51 AM - 05:59 AM',
  },
  {
    id: '5',
    title: 'Sr. Selinta Thought for the Day',
    category: 'Religous',
    time: '06:00 AM - 06:10 AM',
  },
  {
    id: '6',
    title: 'Ayobowan Seth',
    category: 'Entertainment',
    time: '06:11 AM - 07:29 AM',
  },
  {
    id: '7',
    title: 'Paththara Wisthara',
    category: 'Newspaper',
    time: '07:30 AM - 08:00 AM',
  },
  {
    id: '8',
    title: 'Sunday Mass',
    category: 'Religous',
    time: '08:00 AM - 09:00 AM',
  },
  {
    id: '9',
    title: 'Kithunu Gee',
    category: 'Religous',
    time: '09:01 AM - 10:00 AM',
  },
  {
    id: '10',
    title: 'Gee Sandalla',
    category: 'Entertainment',
    time: '10:01 AM - 11:00 AM',
  },

  {
    id: '11',
    title: 'Gee Sandalla',
    category: 'Entertainment',
    time: '11:01 AM - 12:00 AM',
  },
  {
    id: '12',
    title: 'Thunkala Aradhanawa',
    category: 'Religous',
    time: '12:00 PM - 12:05 PM',
  },
  {
    id: '13',
    title: 'Lunch Time Music',
    category: 'Entertainment',
    time: '12:05 PM - 12:45 PM',
  },
  {
    id: '14',
    title: 'Main News',
    category: 'News',
    time: '12:45 PM - 01:00 PM',
  },
  {
    id: '15',
    title: 'Nim Nada Pem Gee',
    category: 'Entertainment',
    time: '01:00 PM - 02:00 PM',
  },
  {
    id: '16',
    title: 'Namasthe',
    category: 'Entertainment',
    time: '02:00 PM - 03:00 PM',
  },
  {
    id: '17',
    title: 'Dewa Dayawa',
    category: 'Religous',
    time: '03:00 PM - 03:29 PM',
  },
  {
    id: '18',
    title: 'Daily Mass',
    category: 'Religous',
    time: '03:30 PM - 04:30 PM',
  },
  {
    id: '19',
    title: 'Nowina',
    category: 'News',
    time: '04:30 PM - 05:00 PM',
  },
  {
    id: '20',
    title: 'Hourly News',
    category: 'News',
    time: '05:00 PM - 05:05 PM',
  },
  {
    id: '21',
    title: 'Gee Sandalla',
    category: 'Entertainment',
    time: '05:06 PM - 06:00 PM',
  },
  {
    id: '22',
    title: 'Seth Evening Request',
    category: 'Entertainment',
    time: '06:01 PM - 06:59 PM',
  },
  {
    id: '23',
    title: 'Catholic Spiritual Program',
    category: 'Religous',
    time: '07:00 PM - 08:00 PM',
  },
  {
    id: '24',
    title: 'Emmaus',
    category: 'Religous',
    time: '08:01 PM - 09:00 PM',
  },
  {
    id: '25',
    title: 'Catholic Hymns',
    category: 'Religous',
    time: '09:10 PM - 09:15 PM',
  },
  {
    id: '26',
    title: 'Seth Main News',
    category: 'News',
    time: '09:15 PM - 09:25 PM',
  },
  {
    id: '27',
    title: 'Holy Rosary',
    category: 'Religous',
    time: '09:30 PM - 10:30 PM',
  },
  {
    id: '28',
    title: 'Night Religous program',
    category: 'Religous',
    time: '10:30 PM - 11:00 PM',
  },
  {
    id: '29',
    title: 'Holy Hour',
    category: 'Religous',
    time: '11:00 PM - 12:00 AM',
  },
  {
    id: '30',
    title: 'Daily Mass - Repeat',
    category: 'Entertainment',
    time: '12:00 AM - 01:00 AM',
  },
  {
    id: '31',
    title: 'Religous Programs',
    category: 'Entertainment',
    time: '01:00 AM - 04:59 AM',
  },
];

const programSchedule = {
  WeekDay,
  Saturday,
  Sunday,
};
export default programSchedule;
